version: '3'

services:
  f1discord-bot:
    image: loafabreadly/simboizbot-bot:latest
    environment:
      - DISCORD_TOKEN=[ DICSORD TOKEN ]
    restart: always
    volumes:
      - /var/dbfiles/:/dbfiles/